# Projects CMakeLists.txt
add_subdirectory(Demo/Display_Demo)
add_subdirectory(Demo/OV5640_I2C1_Init)
add_subdirectory(Demo/Mailbox_Test)
add_subdirectory(Demo/UART3_Echo)
add_subdirectory(Demo/DMA_Interrupt)
add_subdirectory(Demo/DMA_Ram2Ram)
add_subdirectory(Demo/DMA_UART3_Rx)
add_subdirectory(Demo/DMA_UART3_Tx)
add_subdirectory(Demo/FreeRTOS_Shell)
